name: Test

on:
  push:
    branches:
      - blog_creation

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node-version: [ 12.x, 14.x ]
      max-parallel: 24
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm install

      - name: Test
        run: |
          npm test